[[redirects]]
  from = "/api/v1/*"
  to = "http://alizahir327.pythonanywhere.com/api/v1/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
